name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19.0'
    
    - name: Install dependencies
      run: |
        go version
        
    - name: Run build
      run: go build . 
      
    - name: Run vet
      run: |
        go vet .

    - name: Test rules
      run: go test -v ./pkg/rulesConfig/rules_test.go